language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
deploy:
  provider: releases
  user: "davidroyer"
  password: "Dance4life"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
# script:
#   - npm run test:unit
# after_success:
#   - npm run release
# branches:
#   except:
#     - /^v\d+\.\d+\.\d+$/
